
DELETE FROM EMISSIONS_AGRICULTURE_ENERGY WHERE ID IN (SELECT ID FROM EMISSIONS_AGRICULTURE_ENERGY WHERE 
EMISSIONS_AGRICULTURE_ENERGY.ITEM = 'Electricity' AND 
ELEMENT = 'Consumption in Agriculture' AND UNIT = 'Terajoule')